[package]
name = "better-num"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[features]
u8 = []
i8 = []
u16 = []
i16 = []
english = []